### ISSUE TITLE
Teams 1-9 databases not being restored

### ISSUE THREAD

**Issue by happyadam73** [markjones-msft/SQL-Hackathon#3]
Backup files within Zip file for Teams 1-9 are zero padded, i.e. TEAM04_LocalMasterDataDB.bak, but the 2 - RESTORE Databases.sql script uses filenames with no zero padding.

Just need to fix the filenames in the Restore script.  Everywhere else the databases are referred to by zero padding.

**Comment by markjones-msft** [comment]
Fixed
